version: 2
updates:
  - package-ecosystem: "docker"
    directories:
    - "/"
    - "/demo"
    - "/internal/mapper/v017"
    schedule:
      interval: "weekly"
    groups:
      debian:
        patterns:
        - "debian"
      node:
        patterns:
        - "node"
      go:
        patterns:
        - "go"
  - package-ecosystem: "gomod"
    directories:
    - "/"
    - "/tools/benchstat"
    - "/tools/gofumpt"
    - "/tools/goimports"
    - "/tools/golangci-lint"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "weekly"
    groups:
      bootstrap:
        patterns:
        - "bootstrap"
        - "bootswatch"
      vite:
        patterns:
        - "vite"
    open-pull-requests-limit: 10
