# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "master"
  name = "github.com/DeanThompson/ginpprof"

[[constraint]]
  name = "github.com/blang/semver"
  version = "3.5.1"

[[constraint]]
  branch = "master"
  name = "github.com/cnf/structhash"

[[constraint]]
  branch = "master"
  name = "github.com/elazarl/go-bindata-assetfs"

[[constraint]]
  branch = "master"
  name = "github.com/getsentry/raven-go"

[[constraint]]
  branch = "master"
  name = "github.com/gin-contrib/gzip"

[[constraint]]
  branch = "master"
  name = "github.com/gin-contrib/static"

[[constraint]]
  branch = "master"
  name = "github.com/gin-gonic/contrib"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/hansrodtang/randomcolor"

[[constraint]]
  branch = "master"
  name = "github.com/mcuadros/go-gin-prometheus"

[[constraint]]
  name = "github.com/patrickmn/go-cache"
  version = "2.1.0"

[[constraint]]
  name = "github.com/pmezard/go-difflib"
  version = "1.0.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.3"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"

[[constraint]]
  branch = "v1"
  name = "gopkg.in/jarcoal/httpmock.v1"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"
